### ISSUE TITLE
Does not find leveldb dylib newer version (1.22.0) on macos (requires version 1.20)

### ISSUE THREAD

**Issue by lawlawlaw** [commerceblock/cb-electrum-server#12]
When running ./electrumx_server, an older version of leveldb is required (version 1.20 instead of 1.22). Could this be updated to work with 1.22? Otherwise, can the installation instructions be updated?

ERROR:TaskGroup:task crashed: <Task finished coro=<Controller.serve() done, defined at /Users/lawrence/Projects/cb-electrum-server/electrumx/server/controller.py:79> exception=ImportError('dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyvel-1.0.5-py3.6-macosx-10.9-x86_64.egg/plyvel/_plyvel.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/leveldb/lib/libleveldb.1.20.dylib\n  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyvel-1.0.5-py3.6-macosx-10.9-x86_64.egg/plyvel/_plyvel.cpython-36m-darwin.so\n  Reason: image not found',)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiorpcx/curio.py", line 138, in _on_done
    task.result()
  File "/Users/lawrence/Projects/cb-electrum-server/electrumx/server/controller.py", line 100, in serve
    bp = BlockProcessor(env, daemon, notifications)
  File "/Users/lawrence/Projects/cb-electrum-server/electrumx/server/block_processor.py", line 160, in __init__
    super().__init__(env)
  File "/Users/lawrence/Projects/cb-electrum-server/electrumx/server/db.py", line 60, in __init__
    self.db_class = db_class(self.env.db_engine)
  File "/Users/lawrence/Projects/cb-electrum-server/electrumx/server/storage.py", line 20, in db_class
    db_class.import_module()
  File "/Users/lawrence/Projects/cb-electrum-server/electrumx/server/storage.py", line 76, in import_module
    import plyvel
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyvel-1.0.5-py3.6-macosx-10.9-x86_64.egg/plyvel/__init__.py", line 6, in <module>
    from ._plyvel import (  # noqa
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyvel-1.0.5-py3.6-macosx-10.9-x86_64.egg/plyvel/_plyvel.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/leveldb/lib/libleveldb.1.20.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/plyvel-1.0.5-py3.6-macosx-10.9-x86_64.egg/plyvel/_plyvel.cpython-36m-darwin.so
  Reason: image not found
q
^CWARNING:Controller:received SIGINT signal, initiating shutdown
INFO:Controller:shutting down
Traceback (most recent call last):
  File "./electrumx_server", line 30, in main
    controller.run()
  File "/Users/lawrence/Projects/cb-electrum-server/electrumx/lib/server_base.py", line 121, in run
    loop.run_until_complete(self._main(loop))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/Users/lawrence/Projects/cb-electrum-server/electrumx/lib/server_base.py", line 104, in _main
    server_task.cancel()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiorpcx/curio.py", line 254, in __aexit__
    await self.join(wait=self._wait)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiorpcx/curio.py", line 228, in join
    raise TaskGroupError(bad_tasks)
aiorpcx.curio.TaskGroupError: TaskGroupError(ImportError)
CRITICAL:root:ElectrumX server terminated abnormally

**Comment by nkostoulas** [comment]
Probably Mac OS issue. Did you install level db with brew? You might need to re-install plyvel too.

**Comment by lawlawlaw** [comment]
Solved with pip3 install upgrade plyvel
