### ISSUE TITLE
db: flush_count overflow

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/cb-electrum-server#13]
ERROR:TaskGroup:task crashed: <Task finished coro=<BlockProcessor._process_prefetched_blocks() done, defined at /usr/local/lib/python3.6/site-packages/electrumX-1.7.3-py3.6.egg/electrumx/server/block_processor.py:755> exception=error("'H' format requires
0 <= number <= 65535",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiorpcX-0.5.9-py3.6.egg/aiorpcx/curio.py", line 138, in _on_done
    task.result()
  File "/usr/local/lib/python3.6/site-packages/electrumX-1.7.3-py3.6.egg/electrumx/server/block_processor.py", line 760, in _process_prefetched_blocks
    await self._first_caught_up()
  File "/usr/local/lib/python3.6/site-packages/electrumX-1.7.3-py3.6.egg/electrumx/server/block_processor.py", line 776, in _first_caught_up
    self.flush(True)
  File "/usr/local/lib/python3.6/site-packages/electrumX-1.7.3-py3.6.egg/electrumx/server/block_processor.py", line 343, in flush
    hashX_count = self.history.flush()
  File "/usr/local/lib/python3.6/site-packages/electrumX-1.7.3-py3.6.egg/electrumx/server/history.py", line 123, in flush
    flush_id = pack('>H', self.flush_count)
struct.error: 'H' format requires 0 <= number <= 65535

**Comment by nkostoulas** [comment]
from upstream https://github.com/kyuupichan/electrumx/issues/185

**Comment by nkostoulas** [comment]
Need to run compact_history script

**Comment by nkostoulas** [comment]
@stakauskas should we automate the solution to this somehow so that it doesn't come up again?

**Comment by nkostoulas** [comment]
Best run compact_history on entry

**Comment by stakauskas** [comment]
Running on entry should only be a temporary solution to poorly written implementation. It shouldn't require to stop the server once in a while, just to run some scripts and the  start again. Also, adding a run on startup will only fix it for that time. If the server will run long enough, it will again reach a point where it will require downtime to run scripts against the database.

**Comment by nkostoulas** [comment]
@stakauskas @haael can we add this in the ansible tasks? It can run once a month.
